config/routes.rb
Rails.application.routes.draw do
  resources :treatments, except: [:new, :edit]
  get 'home/index'

  resources :patients

  root 'home#index'

    post 'patients/new'
    post 'treatments/new'

    get 'home/index'
    post 'home/profile'

    get 'home/profilepage'

end

app/models/patient.rb
class Patient < ActiveRecord::Base
end

app/models/treatment.rb
class Treatment < ActiveRecord::Base
  belongs_to :patient
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	 protect_from_forgery with: :exception

id=1
  def index
  	@treatments = Treatment.where(isDiagnosed: false)
  	@patients=Patient.all

  end


  def profile

  	patient= Patient.find_by_id(params[:patient_id])
  	id=params[:patient_id]
  	return redirect to '/profilepage'

  	end


  	def profilepage 
  		@patient=Patient.find_by_id(id)
  	end


end

app/controllers/patients_controller.rb
class PatientsController < ActionController::API
  

 def new
        newPatient=Patient.new
        # puts "hddHDHJDHJHJHDDSHDHSDJDS"
        newPatient.name = params["name"]
        # newPatient.address = params["address"]
        newPatient.age = params["age"]
        newPatient.phonenumber= params["phonenumber"] 
        # newPatient.height=params["height"]
        newPatient.weight=params["weight"]
        newPatient.gender=params["gender"]
        newPatient.aadharnumber=params["aadharnumber"]
        newPatient.allergy=params["allergy"]
        newPatient.save

        data={}
        data["message"]="New Patient #{newPatient.name}  created"
        render json:data
  end







end

app/controllers/treatments_controller.rb
class TreatmentsController < ActionController::API

  def new
        newTreatment=Treatment.new
        description="Symtoms:-"


         s1= params['s1'].to_i
         
        if (s1>0)
          description=description+" Headache,"
        end

         s2= params['s2'].to_i
        if (s2>0)
          description=description+"Coughing,"
        end

         s3= params['s3'].to_i
        if (s3>0)
          description=description+'Sneezing,'
        end


       s4= params['s4'].to_i
        if (s4>0)
          description=description+'Running Nose, '
        end


       s5= params['s5'].to_i
        if(s5>0)
          description=description+'Body Pain, '
        end


         s6= params['s6'].to_i
        if (s6>0)
          description=description+'Stomach Ache, '
        end


         s7= params['s1'].to_i
        if (s7>0)
          description=description+'Chest Pain, '
        end


        s8=params['s8'].to_i
        if(s8>0)
          description=description+'Vomiting, '
        end

        temp=params['temp']
        description=description + "Temperature is #{temp}    "

        pulse=params['pulse']
        description=description + "Pulse  is #{pulse}"


        newTreatment.description=description
        newTreatment.isDiagnosed=params["isdiagnosed"]
        aadharnumber = params["aadharnumber"]
        if (Patient.find_by_aadharnumber(aadharnumber))
          p=Patient.find_by_aadharnumber(aadharnumber)
          newTreatment.patient_id=p.id        
          newTreatment.save

          data={}
          data["message"]="New Treatment  #{newTreatment.description} created"
          render json:data

        else
          data={}
          data["message"]="Some problem is the server , Contact Mayank"
       end


  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>
		
	</title>
</head>
<body>




<h1>Listing Treatments</h1>

<table>
  <thead>
    <tr>
      <th>Patient Name</th>
      <th>Aadharnumber</th>
      <th>Age</th>
      <th>Weight</th>
      <th>Phonenumber</th>
      <th>Gender</th>
      <th>Desciption</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @treatments.each do |treatment| %>
      <tr>
      	<% patient=@patients.find_by_id(treatment.patient_id)  %>
        <td> <%= link_to patient.name , url_for(controller: 'home', action: 'profile', :patient_id => patient.id), method: :post %> %></td>
        <td><%= patient.aadharnumber %></td>
        <td><%= patient.age %></td>
        <td><%= patient.weight %></td>
        <td><%= patient.phonenumber %></td>
        <td><%= patient.gender %></td>
        <td><%= treatment.description %></td>
    
      </tr>
    <% end %>
  </tbody>
</table>

<br>



</body>
</html>

app/views/home/profilepage.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
Name :- <%= @patient.name %> 
<br>

Age :- <%= @patient.age %> 
<br> 


</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Finalapi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/patients/_form.html.erb
<%= form_for(@patient) do |f| %>
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% @patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :aadharnumber %><br>
    <%= f.text_field :aadharnumber %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :weight %><br>
    <%= f.number_field :weight %>
  </div>
  <div class="field">
    <%= f.label :phonenumber %><br>
    <%= f.text_field :phonenumber %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.check_box :gender %>
  </div>
  <div class="field">
    <%= f.label :allergy %><br>
    <%= f.text_field :allergy %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<h1>Editing Patient</h1>

<%= render 'form' %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Patients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Aadharnumber</th>
      <th>Age</th>
      <th>Weight</th>
      <th>Phonenumber</th>
      <th>Gender</th>
      <th>Allergy</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.name %></td>
        <td><%= patient.aadharnumber %></td>
        <td><%= patient.age %></td>
        <td><%= patient.weight %></td>
        <td><%= patient.phonenumber %></td>
        <td><%= patient.gender %></td>
        <td><%= patient.allergy %></td>
        <td><%= link_to 'Show', patient %></td>
        <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
        <td><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Patient', new_patient_path %>

app/views/patients/new.html.erb
<h1>New Patient</h1>

<%= render 'form' %>

<%= link_to 'Back', patients_path %>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @patient.name %>
</p>

<p>
  <strong>Aadharnumber:</strong>
  <%= @patient.aadharnumber %>
</p>

<p>
  <strong>Age:</strong>
  <%= @patient.age %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @patient.weight %>
</p>

<p>
  <strong>Phonenumber:</strong>
  <%= @patient.phonenumber %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @patient.gender %>
</p>

<p>
  <strong>Allergy:</strong>
  <%= @patient.allergy %>
</p>

<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Back', patients_path %>